In [1]:
import numpy as np



Примеры создания массивов:
из обычных списков

In [34]:
Example_Variable_1 = np.array([5,6,7,8])
type(Example_Variable_1)

numpy.ndarray

In [16]:
Example_Variable_2 = np.array([[5,6,7,88], [55,66,77,88]])
Example_Variable_2

array([[ 5,  6,  7, 88],
       [55, 66, 77, 88]])

In [17]:
Example_Variable_3 = np.array([[5,6,7,8], [55,66,77,88], [555,666,777,888]])
Example_Variable_3

array([[  5,   6,   7,   8],
       [ 55,  66,  77,  88],
       [555, 666, 777, 888]])

In [18]:
Example_Variable_3.shape

(3, 4)

С использованием функций zeros, ones, arange

In [27]:
Example_Variable_4 = np.arange(0,100,25)
Example_Variable_4

array([ 0, 25, 50, 75])

In [32]:
Example_Variable_5 = np.zeros((3,5,5))
Example_Variable_5

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [33]:
Example_Variable_6 = np.ones((3,5,5))
Example_Variable_6

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

вывод формы (shape) и типа данных (dtype) для одного из массивов.

In [36]:
Example_Variable_7 = np.ones((3,5,5))
Example_Variable_7.shape

(3, 5, 5)

In [37]:
Example_Variable_7.dtype

dtype('float64')

Примеры индексирования и срезов

Получение отдельного элемента

In [72]:
Example_Variable_8 = np.arange(10) **5
Example_Variable_8

array([    0,     1,    32,   243,  1024,  3125,  7776, 16807, 32768,
       59049])

In [69]:
Example_Variable_8[[3]]

array([243])

Извлечение подмассива с помощью среза

In [73]:
Example_Variable_8[0:3]
Example_Variable_8

array([    0,     1,    32,   243,  1024,  3125,  7776, 16807, 32768,
       59049])

Примеры векторных операций и базовых статистик

In [ ]:
Поэлементное сложение и умножение массивов

In [77]:
Example_Variable_9_a = np.array([1, 2, 3, 4, 5])
Example_Variable_9_b = np.array([10, 20, 30, 40, 50])
result = Example_Variable_9_a + Example_Variable_9_b
result

array([11, 22, 33, 44, 55])

In [78]:
Example_Variable_9_a = np.array([1, 2, 3, 4, 5])
Example_Variable_9_b = np.array([10, 20, 30, 40, 50])
result = Example_Variable_9_a * Example_Variable_9_b
result

array([ 10,  40,  90, 160, 250])

Вычисление средней величины (mean) или другой простой статистики.

In [80]:
result.mean()

np.float64(110.0)